"""MVP step 1 — probe every candidate feed and report which ones actually work.

RSS endpoints rot silently. Run this before trusting the collector, and again
whenever daily volume drops. Nothing goes into config/feeds.toml until it has
answered here.

    uv run scripts/check_feeds.py           # probe and report
    uv run scripts/check_feeds.py --write   # also write config/feeds.toml
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from datetime import UTC, datetime, timedelta
from pathlib import Path

import feedparser

ROOT = Path(__file__).resolve().parent.parent
CANDIDATES = ROOT / "config" / "candidates.toml"
FEEDS = ROOT / "config" / "feeds.toml"

# A feed that parses but whose newest item is older than this is dead in practice.
STALE_AFTER = timedelta(days=21)
TIMEOUT = 20

UA = "Nyhetsradar/0.1 (+internal news monitor for Selvaag Eiendom)"


def newest_entry_date(parsed) -> datetime | None:
    """Newest published/updated timestamp across entries, as aware UTC."""
    best = None
    for entry in parsed.entries:
        struct = entry.get("published_parsed") or entry.get("updated_parsed")
        if not struct:
            continue
        when = datetime(*struct[:6], tzinfo=UTC)
        if best is None or when > best:
            best = when
    return best


def probe(name: str, url: str) -> dict:
    """Fetch one feed and classify it as alive / stale / dead."""
    result = {"name": name, "url": url, "status": None, "count": 0, "newest": None}
    try:
        parsed = feedparser.parse(url, agent=UA, request_headers={"Cache-Control": "no-cache"})
    except Exception as exc:  # noqa: BLE001 - any transport failure is just "dead"
        result["verdict"] = "dead"
        result["note"] = f"{type(exc).__name__}: {exc}"
        return result

    result["status"] = getattr(parsed, "status", None)
    result["count"] = len(parsed.entries)
    newest = newest_entry_date(parsed)
    result["newest"] = newest

    # bozo means the body did not parse cleanly as a feed — often a 200 HTML error page.
    if result["count"] == 0:
        result["verdict"] = "dead"
        bozo = getattr(parsed, "bozo_exception", None)
        result["note"] = f"no entries ({bozo})" if bozo else "no entries"
    elif newest is None:
        result["verdict"] = "alive"
        result["note"] = "entries have no dates"
    elif datetime.now(UTC) - newest > STALE_AFTER:
        result["verdict"] = "stale"
        result["note"] = f"newest item {(datetime.now(UTC) - newest).days}d old"
    else:
        result["verdict"] = "alive"
        result["note"] = ""
    return result


def load_candidates() -> list[dict]:
    if not CANDIDATES.exists():
        sys.exit(f"missing {CANDIDATES.relative_to(ROOT)}")
    return tomllib.loads(CANDIDATES.read_text())["candidate"]


def write_feeds(results: list[dict], candidates: list[dict]) -> None:
    """Write config/feeds.toml: live feeds active, everything else commented out."""
    by_url = {c["url"]: c for c in candidates}
    lines = [
        "# Generated by scripts/check_feeds.py — only feeds that responded are active.",
        "# Dead and stale feeds are kept commented out on purpose: the record of what",
        "# was tried is the point. Never delete them.",
        f"# Last probed: {datetime.now(UTC):%Y-%m-%d %H:%M} UTC",
        "",
    ]
    for r in sorted(results, key=lambda r: (r["verdict"] != "alive", r["name"])):
        cand = by_url[r["url"]]
        if r["verdict"] == "alive":
            lines += [
                "[[feed]]",
                f'name = "{r["name"]}"',
                f'url = "{r["url"]}"',
                f'type = "{cand["type"]}"',
                "",
            ]
        else:
            note = r.get("note", "")
            lines += [
                f"# [[feed]]  # {r['verdict'].upper()} {datetime.now(UTC):%Y-%m-%d}: {note}",
                f'#   name = "{r["name"]}"',
                f'#   url = "{r["url"]}"',
                f'#   type = "{cand["type"]}"',
                "",
            ]
    FEEDS.parent.mkdir(parents=True, exist_ok=True)
    FEEDS.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="write config/feeds.toml")
    ap.add_argument("only", nargs="?", help="probe only feeds whose name or url contains this")
    args = ap.parse_args()

    candidates = load_candidates()
    if args.only:
        needle = args.only.lower()
        candidates = [c for c in candidates if needle in c["name"].lower() or needle in c["url"]]
        if not candidates:
            sys.exit(f"no candidate matches {args.only!r}")

    results = []
    print(f"{'verdict':8} {'http':>5} {'items':>6}  {'newest':16}  name")
    print("-" * 78)
    for cand in candidates:
        r = probe(cand["name"], cand["url"])
        results.append(r)
        newest = f"{r['newest']:%Y-%m-%d %H:%M}" if r["newest"] else "-"
        print(
            f"{r['verdict']:8} {str(r['status'] or '-'):>5} {r['count']:>6}  "
            f"{newest:16}  {r['name']}" + (f"  ({r['note']})" if r.get("note") else "")
        )

    alive = [r for r in results if r["verdict"] == "alive"]
    print("-" * 78)
    print(f"{len(alive)} alive / {len(results)} probed")

    if args.write:
        write_feeds(results, candidates)
        print(f"wrote {FEEDS.relative_to(ROOT)}")
    elif alive:
        print("re-run with --write to save config/feeds.toml")

    return 0 if alive else 1


if __name__ == "__main__":
    raise SystemExit(main())
